#!/bin/sh
[ $# -gt 0 ] || { echo "usage: $0 cmd [args...]" >&2; exit 1; }

: "${FIFO_PREFIX:=.}"
in=$FIFO_PREFIX/in
out=$FIFO_PREFIX/out
err=$FIFO_PREFIX/err

printf 'stdin : %s\nstdout: %s\nstderr: %s\n' "$in" "$out" "$err"

"$@" <"$in" >"$out" 2>"$err" &
wait $!
